# Generated by Django 4.1.3 on 2023-01-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_room_creator_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
