# Generated by Django 4.1.3 on 2023-01-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_room_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
    ]
